config/routes.rb
Rails.application.routes.draw do
  resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :content, presence: true, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :destroy]

  def index
    @tweets = Tweet.all
  end

  def new
    if params[:back]
      @tweet = Tweet.new(tweets_params)
    else
      @tweet = Tweet.new
    end
  end

  def create
    @tweet = Tweet.new(tweets_params)
    if @tweet.save
      redirect_to tweets_path, notice: "投稿しました！"
    else
      render 'new'
    end
  end

  def edit
    #@tweet = Tweet.find(params[:id])
  end

  def update
    #@tweet = Tweet.find(params[:id])
    @tweet.update(tweets_params)
    redirect_to tweets_path
  end

  def destroy
    #@tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end

  def confirm
    @tweet = Tweet.new(tweets_params)
    render :new if @tweet.invalid?
  end

  private
    def tweets_params
      params.require(:tweet).permit(:content)
    end

    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yoshitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to tweets_path do %> <i class="fa fa-home"></i>ホーム<% end %></li>
            <li><%= link_to tweets_path do %> <i class="fa fa-search"></i>検索<% end %></li>
            <li><%= link_to tweets_path do %> <i class="fa fa-bell-o"></i>通知<% end %></li>
            <li><%= link_to tweets_path do %> <i class="fa fa-envelope-o"></i>メッセージ送信<% end %></li>
            <li><%= link_to new_tweet_path do %> <i class="fa fa-leaf"></i>ツイート<% end %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>

<%= yield %>

  <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>

</body>
</html>

app/views/tweets/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "Tweet一覧画面にもどる", tweets_path %>

app/views/tweets/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>

    <%= form_for(@tweet) do |f| %>
      <%= f.hidden_field :content %>

      <p>投稿内容:<%= @tweet.content %></p>
      <%= f.submit "投稿する",class: 'btn btn-primary btn-block' %>
    <% end %>

    <%= form_for(@tweet, url: new_tweet_path, method: 'get') do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>投稿を編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>Tweet一覧</h1>
    <% @tweets.each do |tweet| %>
    <div class="row">
      <h4><strong><%= tweet.content %></strong></h4>
      <%= link_to "編集", edit_tweet_path(tweet.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>
<div id="page-tweets-btn" class="page-tweets-btn">
    <p><a class="move-page-tweets" id="move-page-tweets">▲</a></p>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>投稿する</h2>
    <%= render 'form' %>
  </div>
</div>